name: EmpikFoto
options:
  bundleIdPrefix: com.empik
  deploymentTarget:
    iOS: 17.0
targets:
  EmpikFoto:
    type: application
    platform: iOS
    sources:
      - path: EmpikFoto
        excludes:
          - EmpikFotoTests
          - EmpikFotoUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.empik.EmpikFoto
        INFOPLIST_FILE: EmpikFoto/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: Empik Foto
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "Aplikacja potrzebuje dostępu do galerii, aby zapisać utworzony kolaż."
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "Aplikacja potrzebuje dostępu do galerii, aby zapisać utworzony kolaż."
        INFOPLIST_KEY_UILaunchStoryboardName: ""
        INFOPLIST_KEY_UIApplicationSceneManifest_UIApplicationSupportsMultipleScenes: false
        INFOPLIST_KEY_UIApplicationSceneManifest_UISceneConfigurations_UIWindowSceneSessionRoleApplication_0_UISceneConfigurationName: Default Configuration
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "" # Add your development team ID here
  EmpikFotoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EmpikFotoTests
    dependencies:
      - target: EmpikFoto 